name: Workflow Events

on: 
  push:

jobs:
  echo:
    runs-on: ubuntu-lastest
    steps:
      - name: Show the trigger
        run: echo "This workflow was triggered event ${{ github.event_name }} by ${{ github.actor }} on ref ${{ github.ref }}"