name: Contexts
run-name: Contexts | DEBUG - ${{ inputs.debug }}

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        defaults: false
        description: 'Set to true to enable debug mode'

env:
  My_WORKFLOW: 'Workflow'
  My_OVERWRITTEN_VAR: 'WORKFLOW'


jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      My_JOB: 'Job'
      My_OVERWRITTEN_VAR: 'JOB'
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run Id: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"

      - name: Retrieve Variable
        run: |
          echo "The value of the variable is: ${{ vars.MY_VARIABLE }}"

      - name: Print Environment Variables
        env:
          My_OVERWRITTEN_VAR: 'STEP'
        run: |
          echo "My_WORKFLOW env: ${{env.My_WORKFLOW}}"
          echo "My_JOB env: ${{env.My_JOB}}"
          echo "My_OVERWRITTEN_VAR env: ${{env.My_OVERWRITTEN_VAR}}"

