name: Using Expressions in GitHub Actions
run-name: Uisng Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: 'Set to true to enable debug mode'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref}}"
          echo "Commit SHA: ${{ github.sha}}"
          echo "RunnerOS: ${{ runner.os}}"
          
      - name: '[debug] Print when triggered from main'
        if: ${{ inputs.debug && github.ref  ==  'refs/heads/main' }}
        run: echo "This workflow was triggered from the main branch"
      - name: Greeting
        run: echo "Hello, World!"
